# Generated by Django 3.2.16 on 2022-12-23 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('DCare', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Counsel',
            fields=[
                ('cnselno', models.AutoField(primary_key=True, serialize=False)),
                ('cnselask', models.CharField(max_length=300)),
                ('cnselanswer', models.CharField(max_length=600)),
            ],
            options={
                'db_table': 'counsel',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Members',
            fields=[
                ('memno', models.AutoField(primary_key=True, serialize=False)),
                ('mempid', models.CharField(max_length=100)),
                ('memmail', models.CharField(max_length=300)),
                ('mempwd', models.CharField(max_length=100)),
                ('memnm', models.CharField(max_length=100)),
                ('memnick', models.CharField(max_length=100)),
                ('memage', models.IntegerField()),
                ('memgender', models.CharField(max_length=100)),
                ('memtel', models.CharField(max_length=100)),
                ('memaddr', models.CharField(max_length=300)),
                ('memrule', models.IntegerField()),
                ('memimg', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'db_table': 'members',
                'managed': False,
            },
        ),
    ]
